### ISSUE TITLE
카테고리 내 작품이 없을 때 문구 수정

### ISSUE THREAD

**Issue by grace0617** [PrintingAlley/PrintingAlley-iOS#185]
## 🛠 Issue

현재 비어 있는 카테고리 (명함)에서 작품이 없을 때 '설정한 필터에 맞는 검색 결과가 없어요'라고 보여지는데 이것을 바꿔야 할 것 같습니다.

## 📝 To-do

- [x] header: 등록된 작품이 아직 없어요.
- [x] body: 멋진 작품으로 곧 찾아올게요!

<img src = "https://github.com/PrintingAlley/PrintingAlley-iOS/assets/128666933/52ff85e4-679b-446d-addc-b41bd6d0cd1b" width ="250">

**Comment by kpk0616** [comment]
어떻게 바꾸면 될까요 ?? @grace0617

**Comment by grace0617** [comment]
@kpk0616 To do에 적어놓았습니다:) 고마워요 웨스트!
